### ISSUE TITLE
Implement basic olfactory sensor

### ISSUE THREAD

**Issue by grvashu** [simraan9/100DaysOfCode#22]
The agent should now be to able to perceive food in the area of 30 px ahead and 15px behind its nose and flips the direction to get to food quicker.

**Comment by simraan9** [comment]
What is the difference between #21 and #22?

**Comment by simraan9** [comment]
@grvashu

**Comment by grvashu** [comment]
@simraan9 - Eventually they will become eyes and nose. Right now, #21 will allow agent to look forward, and #22 will allow look both sides.
